name: release

on:
  release:
    types:
      - published

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --build-tags integration -p bugs -p unused --timeout=3m

      - name: Make tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build
        uses: fi-ts/action-docker-make@master
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          args: >
            --no-cache
            --build-only metalctl-slug
            -x rule2,rule3
            --summary

      - name: Prepare upload
        run: |
          mkdir -p metalctl/${TAG_NAME}
          sudo chown -R $(id -u):$(id -g) result
          cp result/* metalctl/${TAG_NAME}

      - name: Upload image tarballs to GCS
        run: gsutil -m cp -r -p metalctl gs://$GCS_BUCKET

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            result/metalctl-*