name: release

on:
  push:
    tags:
      - 'v*'

env:
  GCS_BUCKET: images.metal-pod.io
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '278.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Make tag
        run: echo "::set-env name=TAG_NAME::${GITHUB_REF##*/}"
      - name: Build
        uses: metal-stack/action-docker-make@master
        with:
          username: metalstackci
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          args: >
            --no-cache
            --build-only metalctl-slug
            -x rule2,rule3
            --summary
      - name: Prepare upload
        run: |
          mkdir -p metalctl/${TAG_NAME}
          sudo chown -R $(id -u):$(id -g) result
          cp result/* metalctl/${TAG_NAME}
      - name: Upload image tarballs to GCS
        run: gsutil -m cp -r -p metalctl gs://$GCS_BUCKET
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: metalctl ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-linux-amd64
          asset_name: metalctl-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-windows-amd64
          asset_name: metalctl-windows-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-darwin-amd64
          asset_name: metalctl-darwin-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-linux-amd64.md5
          asset_name: metalctl-linux-amd64.md5
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-windows-amd64.md5
          asset_name: metalctl-windows-amd64.md5
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/metalctl-darwin-amd64.md5
          asset_name: metalctl-darwin-amd64.md5
          asset_content_type: application/octet-stream
